### ISSUE TITLE
Guild Conductress 1 and 4 are linked wierd

### ISSUE THREAD

**Issue by Shrinkidge** [sapphireconquer/reportbugs#9]
GC1 takes you to GC4 and GC4 takes you to GC1

Ps. Im Assuming you want to hear about all the bugs so Im hoping Im not an annoyance.

**Comment by sapphireconquer** [comment]
Fixed!

**Comment by Shrinkidge** [comment]
this is actually still not fixed. gc1 from Guild Arena leads to gc4 and gc3 leads to gc2
